# Generated by Django 2.2 on 2019-08-25 18:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190821_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a551be3-a151-4561-bc10-d2282906be70'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
