# Generated by Django 2.2 on 2019-08-25 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190826_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc0b7446-3e15-4965-b5b4-b91c39772632'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
