# Generated by Django 2.2 on 2019-08-26 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190826_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f66c39c8-a6e6-48d2-b7b5-35a414e30e30'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
