# Generated by Django 2.2 on 2019-08-26 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190826_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='language',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f11d38bf-58a1-4ee1-937c-addecd7e3876'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
