# Generated by Django 2.2 on 2019-08-30 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190830_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22181a2e-efe8-444b-95b1-537aaaf39d69'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
